###
#Register a User
POST http://localhost:4000/thot/register/
Content-Type: application/json

{
  "username": "brad johnson",
  "email": "danielokezie76@gmail.com",
  "role": "Retar Manager",
  "password": 1234567
}